package core.enums;

/**
 * 
 * @author Henrique
 *
 */

public enum MissionType
{
    NONE,
    CONSEGUIR_KILL,      //1
    CONSEGUIR_KILL_RIFLE,    //2
    CONSEGUIR_KILL_SUB,      //3
    CONSEGUIR_KILL_SNIPER,   //4 Conseguir Kill
    CONSEGUIR_KILL_SHOTGUN,  //5
    CONSEGUIR_KILL_PISTOLA,     //6
    CONSEGUIR_KILL_FACA,     //7
    CONSEGUIR_KILL_K400,     //8
    CONSEGUIR_DOUBLEKILL,    //9
    CONSEGUIR_DOUBLEKILL_RIFLE,    //10
    CONSEGUIR_DOUBLEKILL_SUB,    //11
    CONSEGUIR_TRIPLEKILL,    //12 Conseguir Double/Triple/Chain Killer
    CONSEGUIR_TRIPLEKILL_SUB,    //13 Conseguir Double/Triple/Chain Killer
    CONSEGUIR_CHAINKILLER,   //14
    CONSEGUIR_HEADSHOT,      //15 Conseguir Head Shot
    CONSEGUIR_HEADSHOT_RIFLE,      //16 Conseguir Head Shot
    CONSEGUIR_HEADSHOT_SUB,      //17 Conseguir Head Shot
    USAR_DERROTAR_RIFLE,      //18
    USAR_DERROTAR_SUB,      //19
    USAR_DERROTAR_SNIPER,   //20 Conseguir Kill
    USAR_DERROTAR_SHOTGUN,  //21
    PIERCINGSHOT, //22
    MASSKILL, //23
    ENTER, //24
    DEATH, //25
    ASSIST, //26
    CHAINSLUGGER, //27
    DEATHBLOW, //28
    DEATHBLOW_RIFLE, //29
    DEATHBLOW_SUB, //30
    DEATHBLOW_SNIPER, //31
    TOUCHDOWN, //32
    WINNER, //33
    ACEATTACKER, //34
    INVASION, //35
    DERROTE_OS_HUMANOS, //36
    CONSEGUIR_KILL_1ROUND, //37
    USAR_DERROTAR_SUB_1ROUND, //38
    ASSIST_TREX, //39
    CONSEGUIR_CHAINKILLER_1ROUND, //40
    CONSEGUIR_TRIPLEKILL_1ROUND, //41
    MATAR_DONO_DA_SALA_1ROUND, //42
    HAT_TRICK, //43
    CONSEGUIR_DOUBLEKILL_1ROUND, //44
    CONSEGUIR_HEADSHOT_1ROUND, //45
    CONSEGUIR_DOUBLEKILL_SNIPER, //46
    CONSEGUIR_CHAINHEADSHOT, //47
    CONSEGUIR_HEADSHOT_SNIPER, //48
    CONSEGUIR_KILL_GRANADA; //49
}