package core.enums;

/**
 * 
 * @author Henrique
 *
 */

public enum MissionEnum
{
    MISSION_NONE,
    MISSION_KILL,
    MISSION_DOUBLEKILL,
    MISSION_TRIPLEKILL,
    MISSION_CHAINKILLER,
    MISSION_HEADSHOT,
    MISSION_PIERCINGSHOT,
    MISSION_MASSKILL,
    MISSION_ENTER,
    MISSION_DEATH,
    MISSION_ASSIST,
    MISSION_CHAINSLUGGER,
    MISSION_DEATHBLOW,
    MISSION_TOUCHDOWN,
    MISSION_WINNER,
    MISSION_INVASION,
    MISSION_ACEATTACKER
}